apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellow-deployment
  labels:
    app: hellow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellow
  template:
    metadata:
      labels:
        app: hellow
    spec:
      containers:
        - name: hellow
          image: sivavel/hellow:latest  
          ports:
            - containerPort: 8080

