name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Generate package.json
      run: |
          if [ ! -f package.json ]; then
            npm init -y
            npm install express
          else
            npm install
          fi
      
    - name: Build Docker Image
      run: docker build -t ${{ vars.DOCKER_USERNAME }}/hellow:2 .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ vars.DOCKER_USERNAME }}/hellow:2

